### ISSUE TITLE
"Int16 out of bounds" messages in log from NodeMarkup when saving a game

### ISSUE THREAD

**Issue by meda22** [MacSergey/NodeMarkup#304]
**Which IMT are you using?  _Stable_**

**What computer OS are you using?  Windows 10**

**Describe the bug**
When I save a game, I can see a lot of messages like following in log:

```
[NodeMarkup] Start save map data
[NodeMarkup] Map data saved in 10ms; Size = 5822 bytes
Int16 out of bounds: 44542
   at System.Environment.get_StackTrace()
   at ColossalFramework.IO.DataSerializer.WriteInt16(Int32 value)
   at BuildingManager+Data.Serialize(ColossalFramework.IO.DataSerializer s)
   at ColossalFramework.IO.DataSerializer.Serialize(System.IO.Stream stream, Mode mode, UInt32 version, IDataContainer data)
   at LoadingManager+<SaveSimulationData>c__IteratorC.MoveNext()
   at AsyncTask.Execute()
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()  [Serialization - Internal]
```

**To Reproduce**
1. Load save game https://steamcommunity.com/sharedfiles/filedetails/?id=2779122444 (though I use around 50 mods and a lot of assets)
2. Save the game and check the output log

**Expected behavior**
So far I don't see any harm done in the save game itself - but I would like to be sure that it's really harmless. Some times it generates quite a huge amount of these error messages.

**Additional information**
I did attached output_log and compatibility report.

[output_log.txt](https://github.com/MacSergey/NodeMarkup/files/8248534/output_log.txt)
[CompatibilityReport.txt](https://github.com/MacSergey/NodeMarkup/files/8248567/CompatibilityReport.txt)

**Comment by meda22** [comment]
Aha, great to know. Then I’m closing this one.
